[package]
name = "uuid-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
mac_address = "1.1.4"
rand = "0.8.5"
uuid = { version = "1.3.0", features = ["v1", "v3", "v4", "v5"] }
